export PORT=9004
export GAMESERVER=http://localhost:9005
export DBNAME=cysecproject
export DBUSER=cysecproj
export DBHOST=localhost
export DBPASSWORD=testpassword
export ADMINUSER=1
export TOKENDECAYTIME=604800000
node index.js