title Gameserver
set PORT=3001
set USERSERVER=http://localhost:3000
set DBNAME=CYSECPROJECT
set DBUSER=root
set DBHOST=localhost
set DBPASSWORD=testpassword
set ADMINUSER=1
set USERSERVERADMINTOKEN=ray2frxosid7nb6dl2vvo4gm5fhu5uyrke0_1
set TOKENDECAYTIME=604800000
nodemon index.js