export PORT=9005
export USERSERVER=http://localhost:9004
export DBNAME=cysecproject
export DBUSER=cysecproj
export DBHOST=localhost
export DBPASSWORD=testpassword
export ADMINUSER=1
export USERSERVERADMINTOKEN=ray2frxosid7nb6dl2vvo4gm5fhu5uyrke0_1
export TOKENDECAYTIME=604800000
node index.js